### ISSUE TITLE
Guardian: Indicate progress / outcomes in RunDKG step

### ISSUE THREAD

**Issue by okjodom** [fedimint/ui#103]
Guardians need to know they are blocked, waiting on all peers to get to `ReadyForConfigGen` state before they can proceed with running DKG. Additionally, we need to communicate outcomes of running DKG, and possibly, consider adding recovery path in case of failure

**Comment by justinmoon** [comment]
Related to https://github.com/fedimint/fedimint/issues/2815

**Comment by EthnTuttle** [comment]
> Related to [fedimint/fedimint#2815](https://github.com/fedimint/fedimint/issues/2815)

This is unblocked.

**Comment by justinmoon** [comment]
> Guardians need to know they are blocked, waiting on all peers to get to ReadyForConfigGen state before they can proceed with running DKG.

What exactly is meant by this? I feel like we already do this but might be missing something.

**Comment by wbobeirne** [comment]
This works well enough today to close this. Any other improvements could be separate issues.
