### ISSUE TITLE
Error in development

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#105]
In development I frequently get this error, which is fixed by "devtools" > "application" > "clear site data" in chrome. It seems to be when my last setup completed and I try to re-run everything.

![image](https://github.com/fedimint/ui/assets/4335621/7a6ed972-c531-44cd-90c9-fb703846d531)

**Comment by wbobeirne** [comment]
This is odd that clearing storage would fix it, it looks like it's this line: https://github.com/fedimint/ui/blob/085f6aa983bf43c652f7efaa5eecdb1255f1aa2c/apps/guardian-ui/src/admin/FederationAdmin.tsx#L108

However this should have just been fetched from the server, so it would seem to mean our type for the status response is incorrect, and sometimes `consensus` is missing? https://github.com/fedimint/ui/blob/085f6aa983bf43c652f7efaa5eecdb1255f1aa2c/apps/guardian-ui/src/types.tsx#L32-L35
