### ISSUE TITLE
Don't hardcode modules in SetConfiguration.tsx

### ISSUE THREAD

**Issue by garyray-k** [fedimint/ui#12]
See TODO in `SetConfiguration.tsx`

_Originally posted by @garyray-k in https://github.com/fedimint/fedimint/pull/2360#discussion_r1186956451_

**Comment by justinmoon** [comment]
I think the big thing is that we shouldn't throw away anything in we receive in `get_default_config_gen_params`. Doing so is what caused the regression fixed by https://github.com/fedimint/ui/pull/106. Our current strategy doesn't notice new defaults.

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/ui/pull/133
