### ISSUE TITLE
Fedimint name not displayed in Dashboard

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#124]
We noticed on the Follower dashboard, the name was not present.
Refreshing a dashboard on an already setup fedimint also does not display the federation name.

**Comment by wbobeirne** [comment]
It looks like the `AdminHeader` component is using the `SetupContext` instead of the `AdminContext`. The former should not be available after setup, we should probably throw if any components try to use it outside of their respective parts of the app.

**Comment by EthnTuttle** [comment]
Blocked by https://github.com/fedimint/fedimint/issues/2451

**Comment by wbobeirne** [comment]
Looks like @okjodom fixed this in #137: https://github.com/fedimint/ui/commit/2f8f87ec929b040b1e6d8a2095c532de18adde23
