### ISSUE TITLE
Display Guardian Name on dashboard

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#140]
Instead of "Peer 0" and "Peer 1", we should display the actual guardian name

![Screenshot 2023-08-15 at 11 19 15 AM](https://github.com/fedimint/ui/assets/133234413/4ffb7b1b-ef12-41b8-89e9-07c768851c89)

**Comment by EthnTuttle** [comment]
Blocked by https://github.com/fedimint/fedimint/issues/2451

**Comment by EthnTuttle** [comment]
<img width="872" alt="Screenshot 2023-08-18 at 11 06 06 AM" src="https://github.com/fedimint/ui/assets/133234413/0510a3bf-95a6-430e-8e9b-a4ccc6bd4474">

**Comment by wbobeirne** [comment]
Closed via #151
