### ISSUE TITLE
FederationAdmin.tsx Dashboard Static Server Health

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#148]
The indicators for the Guardians own server just have static values. We need to hook up to an API (maybe needs backend work?) and determine what metric we're using for this information.

**Comment by wbobeirne** [comment]
Honestly it might just be redundant, we won't have enough information to render anything on the page if the server's in a bad state, and we currently have a dedicated error page for that: https://github.com/fedimint/ui/blob/master/apps/guardian-ui/src/App.tsx#L18-L25.

Might just make sense to axe the pill.

**Comment by EthnTuttle** [comment]
Ack. I'm also a fan of deleting code.
