### ISSUE TITLE
Display assets/liabilities of modules

### ISSUE THREAD

**Issue by elsirion** [fedimint/ui#155]
The audit data is now available via the API and should be used to give the guardians an overview over the amount of BTC in the system and how it is distributed over the different modules.

See fedimint/fedimint#2999

**Comment by wbobeirne** [comment]
The current design for this is just to show Bitcoin assets from the `wallet` module:

<img width="601" alt="Screenshot 2023-09-01 at 11 18 54 AM" src="https://github.com/fedimint/ui/assets/649992/b2d874c3-ee7c-4d4e-bd6d-818a4fc6030c">

I'm not sure this would fit in there, maybe we should have a "Modules" section on the admin that shows which modules are enabled, and what their assets, liabilities, and config options are?

**Comment by elsirion** [comment]
Either that or maybe some summary/details kind of expandable view?

**Comment by Kodylow** [comment]
closed with https://github.com/fedimint/ui/pull/424
