### ISSUE TITLE
Gateway UI: Show real federation title

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#167]
It's currently hard-coded, it should pull from the federation config:

https://github.com/fedimint/ui/blob/dca2a26bb8817c075756e74354cd907ff4b46f23/apps/gateway-ui/src/components/FederationCard.tsx#L17-L25

**Comment by wbobeirne** [comment]
Blocked until https://github.com/fedimint/fedimint/pull/3094 is merged

**Comment by justinmoon** [comment]
^^ got merged
