### ISSUE TITLE
Simplify `GuardianApi` types & implementation

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#176]
From Discord:

> Looking at the `GuardianApi` implementation, is there a reason we split this out into a `BaseGuardianApi` and `GuardianApi`  class, and why we have all these separate interfaces that the classes implement (`implements SocketAndAuthInterface, RpcInterface, SharedApiInterface`)? It feels a little unnecessarily abstracted for what's ultimately just going to be a single API implementation, and requires a lot of duplication of methods.

We can just have a single `GuardianApi` class, and derive its types from the class implementation, rather than defining an interface and having it implement that. That way adding, removing, or updating an RPC method only requires changes in one place.

**Comment by justinmoon** [comment]
I think the pattern of having an interface was originally intended to facilitate having a mock implementation to aid early development. But since we have a real implementation now, I don't think the interface helps at all 👍
