### ISSUE TITLE
Tests for utility functions for millit-sat math

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#182]
https://github.com/fedimint/ui/pull/168#discussion_r1313231511

Add utility functions to ensure accurate conversion of api numbers to UI numbers. These functions should have associated tests.

**Comment by harsh-ps-2003** [comment]
Can you make the issue a bit more clear! I don't see any direct conversion of milli sats to BTC [here](tab:https://github.com/fedimint/ui/blob/5dc4336c7fd57025077943b277ea0bbe313c98b6/apps/gateway-ui/src/components/WithdrawCard.tsx#L99) while it was there earlier [here](tab:https://github.com/fedimint/ui/blob/dca2a26bb8817c075756e74354cd907ff4b46f23/apps/gateway-ui/src/components/WithdrawCard.tsx#L116)! @EthnTuttle

**Comment by wbobeirne** [comment]
It looks like this was already handled with the `formatMsatsToBtc` function that was added. There's still one spot with unclear conversion though, if you want to make or use a util for that and wrap this up: https://github.com/fedimint/ui/blob/5dc4336c7fd57025077943b277ea0bbe313c98b6/apps/gateway-ui/src/components/DepositCard.tsx#L47
