### ISSUE TITLE
Form field for adding arbitrary federation meta key value pairs

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#183]
We currently have a field for federation name, but that actually just sets a field on the meta `{ federation_name: string }`. There are many other fields that could be set, and we won't make custom fields for all of them. We should allow the leader to specify a set of arbitrary key / value pairs. I'm imagining this as a set of side-by-side inputs, with a button to the side to remove them, and a button below to add another pair.

The values will all be coerced to strings since meta is defined as `BTreeMap<String, String>`, however users can input numeric values, JSON objects, or JSON arrays if they wish. We won't easily be able to validate JSON though, unless we use some heuristics (e.g. if it starts with `[` or `{`, validate that it's parseable JSON)

When followers go to verify the config, we should show them all of the key / value pairs.

Docs on meta fields: https://github.com/fedimint/fedimint/blob/master/docs/meta_fields/README.md

**Comment by wbobeirne** [comment]
I started to look at doing a quick pass at this without designs, and just wanted to add a note that the current designs' very narrow template make it hard to do side-by-side fields for key / value inputs. There's very limited space to see the contents. Here was my very ugly first pass:

<img width="412" alt="Screenshot 2023-09-06 at 12 40 15 PM" src="https://github.com/fedimint/ui/assets/649992/3a254110-8cfb-4ba3-afad-30ee9c5ad407">

**Comment by justinmoon** [comment]
Call: first implementation could just be in setup. second round could be updates after dkg.
