### ISSUE TITLE
Admin UI display of federation meta fields

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#184]
We need a section of the admin UI that shows you all of the meta configurations for your federation. These are key value pairs, and they can be extremely large values (giant JSON objects etc) so we have to account for their size. It might be wise to put it in a modal or make it expandable, and to render long values differently than short ones (scrollable code block?)

Blocked by #183, we should add the form fields first.

Docs on meta fields: https://github.com/fedimint/fedimint/blob/master/docs/meta_fields/README.md

**Comment by Kodylow** [comment]
#363 and #362

**Comment by Kodylow** [comment]
https://github.com/fedimint/ui/pull/363
