### ISSUE TITLE
Flow for proposing, reviewing, and approving meta changes

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#185]
We will need a flow in the guardian admin UI that allows guardians to:

1. View the existing meta configuration
2. Propose a change to meta configuration and view the status of the proposal
3. Approve changes proposed to meta configuration
4. Reject changes proposed to meta configuration

Blocked by https://github.com/fedimint/fedimint/issues/2791. Needs #184 as a pre-requisite, and ideally we reuse as much of the designs from #183 for editing the fields.

**Comment by Kodylow** [comment]
I was thinking of drafting something here, would the easiest be like a json editor that shows a diff but the only thing the guardian actually votes on is Yes/No on the new config in its entirety, not like individual items?

**Comment by elsirion** [comment]
> but the only thing the guardian actually votes on is Yes/No on the new config in its entirety, not like individual items?

I think that's how it would work, you vote on a specific new meta field content. That might only be a string or a more complex JSON object, but you don't vote on diffs thereof.

**Comment by Kodylow** [comment]
Done and merged with new meta manager
