### ISSUE TITLE
Move away from `modules_json` RPC method after 0.2 release

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#192]
Let's keep a list of API changes that we should address for the next release:

- Move away from `modules_json` RPC method after 0.2 release https://github.com/fedimint/fedimint/issues/3099
- Update audit rpc call https://github.com/fedimint/fedimint/pull/3090

**Comment by EthnTuttle** [comment]
@justinmoon 
Just pinging this again for discussion during dev call since last activity was Sep.

**Comment by justinmoon** [comment]
We're still a ways away from doing 0.2 release (AlephBFT needs to stabilize) so nothing actionable here

**Comment by okjodom** [comment]
we are closer to 0.2 and the necessary pieces seems to have landed. added this to roadmap and 0.2.1 milestone

**Comment by Kodylow** [comment]
we don't use this anymore, patched out completely. closing
