### ISSUE TITLE
Put some warning in the UI

### ISSUE THREAD

**Issue by dpc** [fedimint/ui#195]
It's like ... 0.1, so ... yeah.

**Comment by wbobeirne** [comment]
Would anyone like to volunteer some copy? We have some designs for alert states so I think that this should work fine on the first page: https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?type=design&node-id=5275-45160&mode=design&t=gvr0jGGf1GpjW0BB-0

**Comment by wbobeirne** [comment]
Came up with a couple of options. One is at the beginning for everyone if we want to be extra scary. The other is a warning at the bitcoin network settings, ONLY if they're on "mainnet"

<img height="300" alt="Screenshot 2023-09-11 at 1 52 37 PM" src="https://github.com/fedimint/ui/assets/649992/f78a43d8-60c7-4da8-9a52-2f1a34c55a1d">
<img height="300" alt="Screenshot 2023-09-11 at 1 52 26 PM" src="https://github.com/fedimint/ui/assets/649992/4dc4aee4-40df-4a71-b4f1-8f1da54b4598">

<br/>

Link to mockups here https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?type=design&node-id=6414-10001&mode=design&t=uedbIlIE6QsRRd9p-0

**Comment by wbobeirne** [comment]
^ The text was for placement only. We should update with some agreed on real copy.
