### ISSUE TITLE
Replace and ban `VStack` and `HStack` components

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#198]
These component adds a `0.5rem` margin to every component after the first, making it difficult to understand when you combine it with flex's `gap` property. For instance, a `<VStack gap={4} />` will product an _actual_ gap of `6`, since `0.5rem` is equivalent to 8 pixels.

We should instead use `<Flex direction="row|column" />` since it doesn't add any default styling.

Bonus points for adding https://eslint.org/docs/latest/rules/no-restricted-imports for `HStack` and `VStack` after the refactor.

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by EthnTuttle** [comment]
> I would like to work on this issue.

Awesome. Please ping in the [Discord](chat.fedimint.org) if you run into any blocker. details for the dev call can be found there as well.
