### ISSUE TITLE
Move release notes to README.md

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#207]
First release notes have a good summary of what's in the repo and running things. This should be migrated to a doc on master somewhere.

**Comment by md-abid-hussain** [comment]
I would like to work on this issue.

**Comment by EthnTuttle** [comment]
> I would like to work on this issue. 

Awesome!
Let us know if you have any questions. Are you a part of our Discord? (chat.Fedimint.org)

**Comment by md-abid-hussain** [comment]
I'm new here so I was not aware of discord channel. I will join it
Thanks if I've any question I'll ask it on channel
