### ISSUE TITLE
Gateway withdrawal modal does not show error

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#219]
If you attempt to withdraw with invalid values (invalid address, invalid amount) the modal just sits there. It should show the error message it gets back from the request.

**Comment by isaacknjama** [comment]
Perhaps it would help to give some guideline alongside the error message since it's not descriptive of the issue causing the request to fail.

**Comment by Kodylow** [comment]
Closing, obivated as part of new gateway UI
