### ISSUE TITLE
Verify Guardians Fuzzing

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#223]
Could have been a one off issue, but I started a local dev fedimint and randomly pasted in the verification strings for the various guardians incorrectly (I did this because I didn't name them well and didn't know which was which). Then most of the guardian UI's were stuck on the verify screen although all string were valid. The backend started throwing errors as well.

Noting here for future investigation to see if it can be reproduced.

**Comment by wbobeirne** [comment]
The verification strings aren't actually posted to the server, we only check the strings locally and then call the `verified_configs` RPC once the user has entered them all: https://github.com/fedimint/ui/blob/13a6517b5a3f81ee8d6c43d5b876c05810210a3f/apps/guardian-ui/src/components/VerifyGuardians.tsx#L100-L109

The backend erroring was likely either related to that call, or something else. Do you still have the logs from then? If you zip up everything in the `$FM_LOGS_DIR` (env var is available in the `user` mprocs tab) then we can look at em.

**Comment by Kodylow** [comment]
closing without replication
