### ISSUE TITLE
Replace environment variables with `config.json` loaded at runtime

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#224]
@elsirion had a brilliant idea: Rather than build-time environment variables and find / replacing the template, we should just load a `/config.json` file. This will make it much easier to change the variables, and make it easier for other projects to server the UI (e.g. `fedimintd`)

The app will make a request to `/config.json` before executing any other code. This may require some refactoring to defer execution of various things until the fetch has happened, and to make configurable properties parameters for functions / classes where they're currently hard-coded.

**Comment by EthnTuttle** [comment]
Does this mean runtime variable for the backend would be configured using `config.json`?
There is only one ENV VAR for the guardian-ui and two for the gateway-ui. Both have one that is the "connection string" for the API. The gateway then has a password, which should probably be refactored out of an ENV VAR.

**Comment by EthnTuttle** [comment]
How do we want to handle changing of `config.json` during runtime? A hard refresh of the app might have it reconnect to a different mint than what was initialized with. These seems desirable but we'll have to account for it with the State management.

**Comment by elsirion** [comment]
Re state mgmt: I noticed that properly restarting the setup process is hard/impossible. Even after deleting all state of `fedimintd`+restarting it the UI was still at the old state after a reload. I'd expect it to reinitialize its state from the federation after a reload.

**Comment by EthnTuttle** [comment]
> Re state mgmt: I noticed that properly restarting the setup process is hard/impossible. Even after deleting all state of `fedimintd`+restarting it the UI was still at the old state after a reload. I'd expect it to reinitialize its state from the federation after a reload.

I haven't looked yet through the code but perhaps it can be asked during the dev call.
Is there a good API for this? Maybe a deep dive on setup API?

**Comment by justinmoon** [comment]
> Re state mgmt: I noticed that properly restarting the setup process is hard/impossible. Even after deleting all state of `fedimintd`+restarting it the UI was still at the old state after a reload. I'd expect it to reinitialize its state from the federation after a reload.

Call: this might have been a side-effect of setting admin password via environment variable

**Comment by EthnTuttle** [comment]
@wbobeirne 
Can you peak `config-json-reboot` branch? I feel I am close but would appreciate feedback if I'm going off course.
