### ISSUE TITLE
UI is dropping some params given to default template

### ISSUE THREAD

**Issue by douglaz** [fedimint/ui#237]
This was implemented: https://github.com/fedimint/fedimint/pull/3126

But it seems to get removed by the UI during the setup process. A brief investigation:

I added a `FM_EXTRA_DKG_META=chat_server_domain=xmpp.89b8916b.hexip.net` to fedimintd env, and we see that at first it was on the default config gen params:

![image](https://github.com/fedimint/ui/assets/163706/fc90998b-9c7e-434c-a823-ac4c243873b0)

Then the params were set without this value:
![image](https://github.com/fedimint/ui/assets/163706/810b0b22-ec81-4151-831c-699b4eb2146a)

And of course it was not returned after that:
![image](https://github.com/fedimint/ui/assets/163706/9d5ebd12-ba58-422d-ba15-bec25e0b16e0)

**Comment by EthnTuttle** [comment]
#183 
Related.

**Comment by EthnTuttle** [comment]
I wonder if this is a serialization thing since the `MetaConfig` type only has one field on it.
```ts
export type MetaConfig = { federation_name?: string };
```
