### ISSUE TITLE
Can restart fedimint setup

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#253]
Sometimes setups fail in a way that could be avoided if they were attempted again.

**Comment by Kodylow** [comment]
Is there already an exposed api for doing the hard reset server side from fedimint?

**Comment by justinmoon** [comment]
> Is there already an exposed api for doing the hard reset server side from fedimint?

No, so creating that would be part of the fix.

**Comment by okjodom** [comment]
I'm looking at the setup rpc method for restart
