### ISSUE TITLE
Handle being in `VerifiedConfigs` when leader is in `ConsensusRunning`

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#255]
We've got a potential bug where if you refresh the page after the leader has run `startConsensus`, you get stuck as a follower since you can no longer fetch their config. We're actually ready to go, we just need to call `startConsensus` at this point, but we have no UI to do it because it shows an error.

Not 100% sure the best thing to do here, automatically do it for the user? Show them a button?

**Comment by justinmoon** [comment]
Another option would be to have the "status" and "config hashes" rpc commands to also be available in the fedimint consensus API is running. Root problem here is that those RPC commands disappear when the config API is taken down in order to run the consensus API.

**Comment by justinmoon** [comment]
@douglaz @okjodom Would we be able to continue serving [get_verify_config_hash](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/net/api.rs#L604-L610) in the consensus API?

[It seems to just need the peer TLS certs](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/config/api.rs#L274-L294). Looks like these are [in the consensus config](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/config/mod.rs#L139)?

If we continued to serve this endpoint, then a user who gets stuck in the config verification step would be able to recover.

**Comment by okjodom** [comment]
> @douglaz @okjodom Would we be able to continue serving [get_verify_config_hash](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/net/api.rs#L604-L610) in the consensus API?
> 
> [It seems to just need the peer TLS certs](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/config/api.rs#L274-L294). Looks like these are [in the consensus config](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/config/mod.rs#L139)?
> 
> If we continued to serve this endpoint, then a user who gets stuck in the config verification step would be able to recover.

Looks feasible!
