### ISSUE TITLE
Improve mobile UX

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#264]
All our designs are for desktop, but lots of people end up using mobile phones for the setup

**Comment by sahilc0** [comment]
Working on it here: https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?type=design&node-id=6764-6643&mode=design&t=vBUcQSIW1dLRmBnz-11

**Comment by sahilc0** [comment]
Spec here cc @Kodylow I believe you were going to take a look

cc @skylerwww if any design feedback https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?type=design&node-id=6775-11770&mode=dev
