### ISSUE TITLE
Re-enable solo federations

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#266]
With https://github.com/fedimint/fedimint/pull/3505 merged, we can do solo federations again. We should update validation to allow 1 or 4+, but not 2 or 3 person federations.

**Comment by wbobeirne** [comment]
One possibility to simplify the UI a bit for solo federations is for it to be its own option. We'll hide the `Number of guardians` input and remove the invite step. Then for the leader option, we'll just force 4+ peers. LMK what y'all think.

![CleanShot 2023-11-06 at 16 46 22@2x](https://github.com/fedimint/ui/assets/649992/bc11ffe9-8743-4cec-8be7-61db9ecb5034)

**Comment by Kodylow** [comment]
On clovyr we have 2 different setups: federation guardian and developer all-in-one. We could just enable solo federations for the all in one (comes packaged with lightning gateway too) and keep it as 4 for the guardian-ui?

**Comment by bprice6** [comment]
I like the layout you have Will for a solo guardian - it'd be great if we had a quick note that 2/3 guardians isn't supported as well.

**Comment by obi** [comment]
I like this idea if it is such to implement. Simplifies the set up.UX for those wanting to solo guardians.

**Comment by EthnTuttle** [comment]
Do we have a write up of what a developer might be lacking if they use solo-mode? I see that the design calls out no consensus but could that be more clearly articulated to a dev that's unfamiliar with Fedimint? Or developing for the first time?

**Comment by humansinstitute** [comment]
Agree with Will on this, shortcutting to its own option would be preferable from a UX point of view and a "Solo" federation seems like a special case.

**Comment by wbobeirne** [comment]
Agreed with @EthnTuttle, I could definitely use some help with the copy to better explain to the user what this choice means. The biggest thing I'm aware of is that you only have a single source of truth, so you'd need to make your own backups, and you have no redundancy, so if your server goes down then the whole federation goes down. Not sure if there are any other major ramifications aside from just everyone who connects to the federation has only one individual to trust instead of a group.

**Comment by EthnTuttle** [comment]
Is this only desired if running in a Dev environment?

------- Original Message -------

**Comment by Kodylow** [comment]
Copy recommendation:

"Running as a Solo guardian operates without consensus, fault-tolerance, federated backups, or other resilience benefits from running a multi-guardian federation. Proceed with caution."

and could make the highlight be yellow or red instead of blue.

**Comment by okjodom** [comment]
closed by #325
