### ISSUE TITLE
Guardian Balance should show all ecash in the federation, not net assets

### ISSUE THREAD

**Issue by Kodylow** [fedimint/ui#282]
<img width="665" alt="image" src="https://github.com/fedimint/ui/assets/74332828/ed33fac3-6db3-48f5-aab6-ba89d63f7f48">

I think this would make more sense to show all the issued ecash, then maybe we could do the specifics like net under it in gray text. But showing balance as 0 by netting out the gateway seems inaccurate to what the guardian would want to know which is the current reserves of the federation.

**Comment by justinmoon** [comment]
I don't understand what you mean. Wallet module net assets are how much bitcoin is in the federation. Those balances show up the same regardless of whether the gateway deposited them or not.

In the future we should present a balance sheet of the federation: all assets, and all liabilities split out by contract type. That way you could see how much is locked up in different modules / contracts etc. Ecash is one type of liability, but lightning contracts are also forms of liability.

**Comment by Kodylow** [comment]
Done with new balance sheet
