### ISSUE TITLE
Mobile UI: Collapsible sections for configuration options

### ISSUE THREAD

**Issue by Kodylow** [fedimint/ui#294]
For mobile @sahilc0 redesigned to have the sections collapsible. Couple pending questions on this:

Should they be by default all open then on each section they click "Approve" which collapses it and sets the green checkmark? then next only becomes enabled once all sections are approved?

I like the sections for it generally though and we could probably improve them on desktop too.

![image](https://github.com/fedimint/ui/assets/74332828/9ec86ffd-fd9a-4c9f-a726-bcf2ff149893)

Only thing missing here is meta fields, @sahilc0 can you do design for what that section looks like when opened? It's different from the other ones because the inputs are side by side on mobile. want to do the same switch to stacked like you had for the verify guardians? But have to be able to put in both key and value

![image](https://github.com/fedimint/ui/assets/74332828/70535349-f67e-4b83-9396-2f6cb7198c1e)

**Comment by wbobeirne** [comment]
It's worth noting this is not a mobile-specific design, this is the intended design of the desktop as well: https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?type=design&node-id=503-24661&mode=design&t=qaFRArbGJYq1PxFq-0

![Federation details](https://github.com/fedimint/ui/assets/649992/714a374f-5324-417b-9cd5-4297f7c8006b)


> Should they be by default all open then on each section they click "Approve" which collapses it and sets the green checkmark? then next only becomes enabled once all sections are approved?

I'd say let's not complicate things; I think the intent was just to have them all collapsed by default unless they require input from the user. So if they start off valid, they should be collapsed unless someone wants to modify them.

**Comment by Kodylow** [comment]
Views updated for desktop and mobile in #303 draft

**Comment by Kodylow** [comment]
Closed #303 in favor of #310

**Comment by Kodylow** [comment]
closed by #310
