### ISSUE TITLE
Remove "Sharing info between Guardians" Copy - just "Success"

### ISSUE THREAD

**Issue by Kodylow** [fedimint/ui#295]
This copy specifically takes up a ton of space on mobile, and it's redundant given the "Running some numbers" copy below:

![image](https://github.com/fedimint/ui/assets/74332828/4a3b813e-b1e5-43cf-8570-95ca34bd763f)

**Comment by wbobeirne** [comment]
> just "Boom"

I think this is gonna be pretty confusing to non-English speakers (and honestly, kinda confusing to English speakers as well.) Boom kinda sounds like something bad happened 😅

**Comment by Kodylow** [comment]
Can we change to "Success" then?
