### ISSUE TITLE
`nix-guardian` running 2 UIs against the same Fedimintd instance

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#297]
Started running into this on `master` for the first time recently, two of the `guardian-ui` instances are hitting the same WS api despite being started with different environment variables:

![Frame 10](https://github.com/fedimint/ui/assets/649992/a7d1c140-716a-4e9c-8465-eda6c9ce2ce4)

Not sure what's causing this, but as you can expect this makes completing a setup impossible.

**Comment by wbobeirne** [comment]
This can be remedied by restarting the offending `guardian-ui` instance. In this case, restarting `guardian-ui-4` on `localhot:3003` correctly had it hitting port `18144` instead.

**Comment by Kodylow** [comment]
fixed already
