### ISSUE TITLE
Internationalization of UI

### ISSUE THREAD

**Issue by garyray-k** [fedimint/ui#3]
Lay some framework for translating.

fwiw, I've seen json files work nicely for this.
i.e. 

en.json
```json
{
    "dashboard": {
        "title": "Fedimint Guardian Dashbaord"
    }
}
```

es.json
```json
{
    "dashboard": {
        "title": "Panel de Guardian de Fedimint"
    }
}
```

It's then reference in typescript:
```tsx
<Text>
    {i18n.dashboard.title}
</Text>
```

**Comment by EthnTuttle** [comment]
https://locize.com/

I emailed this company since they have special deals for open source projects. They said to integrate with their service using the free trial and they'll assess our usage for potential sponsorship.

I imagine this would be worth exploring. They created the framework we started using and offer commercial services for it via locize.

Full text of the email here:
> Hi Ethan,
> 
> Yes, if your project is open source and non-profit, without any commercial product related to the open-source project we can offer a special discount.
>
> But to do so we need to know more about your usage… We suggest you create a new locize project and integrate it in to your code.
> During the trial test everything you like to, and then we can check what usage you have (amount of words, etc…)
> For example if you have not so many words and are not using our CDN (generate downloads), we may also think to sponsor your locize project completely. In that case it would be nice if you could add our logo with a link to locize.com somewhere on your side.
>
> Let me know what you think about that.
> 
> Best regards, Adriano
> locize.com

**Comment by benalleng** [comment]
> We suggest you create a new locize project and integrate it in to your code.

For further enhancing the i18next framework i have been building would we want to transition over from the json files to using their backend instead like they mention in their [documentation](https://docs.locize.com/integration/instrumenting-your-code)?
