### ISSUE TITLE
Local Storage invalid between federation clear and restart

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#32]
I believe this should only impact dev environments since reproducing this is pretty far out there for an edge cases. 

We default to local storage to hydrate SetupContext so if you restart/clear a federation in the middle of setup, the UI will see that there is already SetupContext state in local storage and hydrate the context.  This will not match the actual state of the backend.

To reproduce:
1. startup a local federation and continue through only part of the setup flow (stopping around verify guardians or some other intermediary step)
2. Stop the fedimintd instances and clear the federation data.
3. Restart fedimintd instances.
4. Browse to Setup UI and refresh. You should see an error (The websocket is not opened) or similar.
5. Check local storage cache and observe.
<img width="641" alt="Screenshot 2023-06-12 at 7 58 19 AM" src="https://github.com/fedimint/ui/assets/133234413/1edd5863-6d25-4de7-8db6-327ce357916f">

**Comment by wbobeirne** [comment]
This block was intended to check the current state of the server, and reset the local state if the server's status doesn't jive with our local state: https://github.com/fedimint/ui/blob/be47100bffe2804286f289c3149871ebea0ae59a/apps/guardian-ui/src/setup/SetupContext.tsx#L130-L196. This made the assumption that the fresh restart would put you into `AwaitingPassword`. If that assumption is no longer true, we can probably add some additional logic in here to reset for other cases.

I was also considering if we should always just prompt the user if they load the page with mid-setup state, letting them know they can either continue from when they last left off, or to start over. That might cut through a lot of these cases.

**Comment by okjodom** [comment]
no repro after #104 . Please confirm?

**Comment by wbobeirne** [comment]
I've run through the wipe to restart case a few dozen times in the past couple days with no issue, so I'm going to close. In the OP's picture, it looks like they had a websocket connection issue so the client did not yet know it was a restarted instance for it to wipe state. I believe if the websocket had properly connected, it would have received a status of `AwaitingPassword` and fixed itself as expected.

Please re-open with repro steps if I'm wrong!
