### ISSUE TITLE
Lightning Node Id is wrong

### ISSUE THREAD

**Issue by douglaz** [fedimint/ui#336]
It shows:
![image](https://github.com/fedimint/ui/assets/163706/ece2b326-7f56-4fb7-a1e5-93f24d28ad45)

But it's:
![image](https://github.com/fedimint/ui/assets/163706/d636008f-1c5d-4088-8e3c-23f5e6fbaccf)

**Comment by wbobeirne** [comment]
https://github.com/fedimint/ui/blob/6384ecab78aaa9b816a598ee1a0ef0527d959252/apps/gateway-ui/src/components/FederationCard.tsx#L38

lol.
