### ISSUE TITLE
Guardian cannot remove meta fields during setup

### ISSUE THREAD

**Issue by Kodylow** [fedimint/ui#344]
![image](https://github.com/fedimint/ui/assets/74332828/18e22f74-528d-4aa8-8b45-6e37b5ea060a)

Guardian (Solo or Leader) needs to be able to remove unused meta fields

**Comment by wbobeirne** [comment]
There is supposed to be a trash can to the right of the field. I think some of the mobile updates are hiding it with an `overflow: hidden`.

https://github.com/fedimint/ui/blob/2a65c4ad2e3faf919baed210acb7106fac03fe48/apps/guardian-ui/src/components/MetaFieldFormControl.tsx#L82-L98

**Comment by wbobeirne** [comment]
And FWIW that same overflow hidden is causing the inputs to look "cut off" on the sides when they're focused, would be nice to fix that too.

**Comment by Kodylow** [comment]
Yup there it is, pushing up a fix rn:

![image](https://github.com/fedimint/ui/assets/74332828/262f8c52-e15d-412d-8781-08a23f020433)
