### ISSUE TITLE
spanish translations not working everywhere

### ISSUE THREAD

**Issue by Kodylow** [fedimint/ui#350]
<img width="823" alt="image" src="https://github.com/fedimint/ui/assets/74332828/c83748f2-5f91-4dc9-801d-669d6e5087de">

**Comment by isaack-njama** [comment]
I've been looking into this and observed:
1. For `Solo Federations`, there is no Spanish translation for Title and Subtitle
2. For `Solo Federations`, there is no Spanish translation for Role Selector Description

Also my experience enabling Spanish translation on Firefox:
1. Translations do not persist during browser reload
2. However, this behaves different when the `i18nextLng` key in localStorage is changed to `es` or `es-ES` - translations persist.
3. Getting translations to work on Chrome and Brave has been a challenge on my end. While this was pretty straightforward and simple on Firefox, modifying the Language settings on Chrome and Brave doesn't automatically get translations to work


@Kodylow @okjodom

**Comment by Kodylow** [comment]
I'll do a run through of the translation files today to address any missing items, good catch
