### ISSUE TITLE
leader should not restart after peers have moved to consensus running

### ISSUE THREAD

**Issue by okjodom** [fedimint/ui#358]
After one or more peers have  successfully set up their nodes (servers in `consensus_running` state) we should prevent the leader from initiating setup restart
![image](https://github.com/fedimint/ui/assets/11217077/1445b0a3-3335-419b-a7e9-ccbbdee1034a)

**Comment by okjodom** [comment]
> Does this need to be tracked in feimint/fedimint too? Sounds like the underlying issue might be there?

Tracking with https://github.com/fedimint/fedimint/issues/4124

**Comment by Kodylow** [comment]
closing in favor of tracking issue: https://github.com/fedimint/ui/issues/474
