### ISSUE TITLE
Create Paneled Experience in Federation Admin UI

### ISSUE THREAD

**Issue by okjodom** [fedimint/ui#37]
Ref: [Figma](https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?type=design&node-id=1469-22301&t=4OcWti0KH5jAyXK9-0)

Initialize side main panel experience of the admin ui dashboard. Main panel would just contain the elements we presently have prototyped in the admin ui

**Comment by okjodom** [comment]
cc @IgboPharaoh

**Comment by IgboPharaoh** [comment]
Great, I'll start working on this.
I'll look through the design and send any possible questions
