### ISSUE TITLE
Guardian should be able to download backup from UI

### ISSUE THREAD

**Issue by Kodylow** [fedimint/ui#387]
Now that https://github.com/fedimint/fedimint/pull/4415 landed fedimintd supports letting the guardian download a backup, we need to add this to the UI with warnings about keeping it safe and a link to instructions on how to recover with it.

**Comment by elsirion** [comment]
If they chose a good password the backup isn't all that confidential. It's more important to remind them that without the password it isn't worth anything.

**Comment by Kodylow** [comment]
PR up https://github.com/fedimint/ui/pull/388

**Comment by Kodylow** [comment]
closed with PR

**Comment by Kodylow** [comment]
closed with https://github.com/fedimint/ui/pull/388
