### ISSUE TITLE
Fedimint does not return federationId in the config

### ISSUE THREAD

**Issue by Kodylow** [fedimint/ui#390]
Found some discrepancies between our typescript API and the rust code.

We expect a federationId and other keys from the client config which are not returned by the rust code. I'm putting up a PR to add it fedimint side since it's useful and I want to use it for guardian auth

typescript:
```typescript
interface ClientConfig {
    consensus_version: CoreConsensusVersion;
    epoch_pk: string;
    federation_id: string;
    api_endpoints: Record<number, ApiEndpoint>;
    modules: Record<number, FedimintModule>;
    meta: MetaConfig;
}
```

rust:
```rust
/// Total client config
///
/// This includes global settings and client-side module configs.
#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize, Encodable, Decodable)]
pub struct ClientConfig {
    #[serde(flatten)]
    pub global: GlobalClientConfig,
    #[serde(deserialize_with = "de_int_key")]
    pub modules: BTreeMap<ModuleInstanceId, ClientModuleConfig>,
}

pub struct GlobalClientConfig {
    /// API endpoints for each federation member
    #[serde(deserialize_with = "de_int_key")]
    pub api_endpoints: BTreeMap<PeerId, PeerUrl>,
    /// Core consensus version
    pub consensus_version: CoreConsensusVersion,
    // TODO: make it a String -> serde_json::Value map?
    /// Additional config the federation wants to transmit to the clients
    pub meta: BTreeMap<String, String>,
}
```

**Comment by okjodom** [comment]
Latest `ClientConfig` returned by the API includes these fields
![Image](https://github.com/fedimint/ui/assets/11217077/3e5319ec-a7b4-496e-8ab8-415456b8e88f)

making an update to remove `epoch_pk` which I think lingered since the days of HBBFT

**Comment by elsirion** [comment]
The problem was solved differently on the Fedimint side: https://github.com/fedimint/fedimint/pull/4576, is this issue still relevant @Kodylow?

**Comment by okjodom** [comment]
> The problem was solved differently on the Fedimint side: [fedimint/fedimint#4576](https://github.com/fedimint/fedimint/pull/4576), is this issue still relevant?

After the upstream fix, we can now add a new rpc call to Typescript api to get the federation id.
The part about typescritpt types being stale is still relevant. Fixed by https://github.com/fedimint/ui/pull/400
