### ISSUE TITLE
UI looks quite bad in dark mode

### ISSUE THREAD

**Issue by elsirion** [fedimint/ui#395]
See https://github.com/fedimint/ui/pull/394#issue-2190123087

![Screenshot from 2024-03-16 19-37-05](https://github.com/fedimint/ui/assets/41724425/f003d7e8-cfae-42c6-ab9f-a863e68b08a4)

**Comment by justinmoon** [comment]
@isaack-njama Is this dark mode a browser extension? Or a mode of the guardian UI? IIRC we removed dark mode from the guardian UI a while back https://github.com/fedimint/ui/issues/16

**Comment by isaack-njama** [comment]
> @isaack-njama Is this dark mode a browser extension? Or a mode of the guardian UI? IIRC we removed dark mode from the guardian UI a while back #16

The dark mode is from setting the `chakra-ui-color-mode` on local storage to `dark`. 

I always had it set to `dark`, light mode hurts my eyes.

**Comment by elsirion** [comment]
So this won't happen to other users?

**Comment by isaack-njama** [comment]
> So this won't happen to other users?

Not really, unless the value is set manually.
