### ISSUE TITLE
Support multiple networks configured vis SetupUI

### ISSUE THREAD

**Issue by okjodom** [fedimint/ui#41]
Setup UI should support setting up federations on
- [ ] Testnet
- [x] Regtest
- [ ] Signet
- [ ] Mainnet

**Comment by IgboPharaoh** [comment]
Hello I'll like to work on this issue

**Comment by okjodom** [comment]
Still an issue because a user has to select the right network as configured in deployed bitcoin service. Selecting any other network is not supported

**Comment by okjodom** [comment]
Actually, the issue with switching network at runtime is discussed in #4. Closing this one as duplicate
