### ISSUE TITLE
Try CodeRabbit for UI repo

### ISSUE THREAD

**Issue by elsirion** [fedimint/ui#410]
We tried the https://app.coderabbit.ai/ review AI on Fedimint and it was too noisy, but given how little review the UI repo gets since most core Fedimint contributors don't know the front end tech stack, maybe it would make more sense here?

**Comment by maan2003** [comment]
and AI is probably better at understanding at javascript

**Comment by elsirion** [comment]
@Kodylow, @okjodom do you want to give it a shot?

**Comment by okjodom** [comment]
> @Kodylow, @okjodom do you want to give it a shot?

Cant help set it up, but I'm open to see how it fares on this repo

**Comment by Kodylow** [comment]
Yeah sure sounds fun

**Comment by elsirion** [comment]
We have to pay per seat, so for now I only activated it for you two, lmk if others are contributing a lot and should get access.

**Comment by Kodylow** [comment]
update: it's been OK, sometimes useful, very noisy. Good to continue using it for now but if there's any seetings we can tweak for it to muffle a little that'd be nice.

**Comment by elsirion** [comment]
There is a way to add a prompt, I told it to be concise and not add nits.

**Comment by Kodylow** [comment]
closing

**Comment by elsirion** [comment]
Good reminder, we tried it out for a while now, is it overall useful or should I turn it off?

**Comment by Kodylow** [comment]
I really like it especially now that it's basically just me haha, It's pretty great at sanity checking when I solo yolo stuff
