### ISSUE TITLE
Wrong button text

### ISSUE THREAD

**Issue by elsirion** [fedimint/ui#417]
![Screenshot 2024-04-21 at 23-45-05 Guardian UI](https://github.com/fedimint/ui/assets/84478054/6299fc9e-56e8-486f-ad10-9ab7685a7e83)

Before showing the admin auth QR the guardian is presented with this dialog. "Acknowledge+Download" should be "Proceed" or similar imo (there is no download).

**Comment by Dayvvo** [comment]
Funny how I thought something similar when trying to run the app today. Mind if I fix this @elsirion ?
