### ISSUE TITLE
feat: add support to connect to server over Tor

### ISSUE THREAD

**Issue by oleonardolima** [fedimint/ui#442]
I've been trying to do an federation setup over Tor since the start, currently the UI does not have support to connect to the Federation API over Tor.

It's part of https://github.com/fedimint/fedimint/issues/2610

**Comment by oleonardolima** [comment]
In reality, I don't think any change is needed, the failure that I was having was due to the setup on my side. In the end, it worked over hidden services without a problem.

**Comment by elsirion** [comment]
Sounds like we can close this one then and track Tor support in the main issue?
