### ISSUE TITLE
Gracefully Handle Setup to Consensus API switch

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#47]
In `apps/guardian-ui/src/GuardianApi.ts` the `startConsensus` method is flaky due to how we currently handle the API switch. The UI gets caught in a "setup" state but in reality, consensus has already started running. A refresh of the UI leads to "method not found" errors as it tries to determine where in the setup process is it.

I have tried a few approaches but none have yielded consistent results.

relevant Discord conversations:
https://discord.com/channels/990354215060795454/990354215878688860/1122657638388338819
https://discord.com/channels/990354215060795454/990354215878688860/1124158861876674571
https://discord.com/channels/990354215060795454/1105908596614627428/1121760876286976071

**Comment by wbobeirne** [comment]
Can we close this thanks to #52?
