### ISSUE TITLE
Docker-compose Gatewayd <-> LND

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#48]
Currently the gatewayd doesn't connect to LND in the dev docker-compose setup.

<img width="1021" alt="Screenshot 2023-07-03 at 12 55 42 PM" src="https://github.com/fedimint/ui/assets/133234413/124a6f90-4d2c-4b97-a58e-f469c01fdfd6">

**Comment by EthnTuttle** [comment]
cc: @justinmoon

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/ui/pull/55
