### ISSUE TITLE
Next button inactive in solo federation setup

### ISSUE THREAD

**Issue by f321x** [fedimint/ui#510]
When trying to setup a mainnet solo federation the next button stays inactive even after filling in all information. There is no way to continue the solo setup. Tried copy pasting the information back in, reloading the page, etc. 
Seems to work fine in a normal (multi) guardian setup.
Tested in Firefox 129.0.2 and Chromium 127.0.6533.119. Fedimint and Guardian UI v0.4.1 running as docker setup.
Edit: 
I think its a problem with FederationSettingsForm not showing up in solo setup, the next button seems to need a Federation Name to activate but the FederationSettingsForm seems be hidden in solo setup.

![Screenshot from 2024-08-24 10-45-05](https://github.com/user-attachments/assets/9f830bd6-bdf7-443c-93aa-788e08f13b59)

**Comment by elsirion** [comment]
Which version of the UI did you deploy? This looks like a rather old one, it doesn't have automatic password generation yet (at least I assume we implemented that for all setup flows @Kodylow?).

**Comment by f321x** [comment]
This is Guardian UI v0.4.1 (fedimintui/guardian-ui:0.4.1 docker container), the screenshot is after i pressed generate password.

**Comment by Kodylow** [comment]
This is fixed on master and will be out in the next point release for 0.4.2 that I'm cutting today/tomorrow (landing one more PR and testing it before cut.

Once that's out just run docker compose down, change the image to 0.4.2, then docker compose up and it'll be good to go.

Will post here and tag you when it's cut

**Comment by f321x** [comment]
Just tested the new 0.4.2 tag, works fine now, thanks for the quick fix!
