### ISSUE TITLE
Dockerfile.guardian-ui builds static assets at runtime

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#58]
This is memory intensive. Failed on $6 digital ocean server. Eventually just embed the `build/` directory when we create the container. This line:

```
CMD if [ ! -z "$REACT_APP_FM_CONFIG_API" ]; then yarn build;fi && serve -s apps/guardian-ui/build/
```

**Comment by wbobeirne** [comment]
This was fixed by #72 (and #74 fixes some issues with #72)
