### ISSUE TITLE
CI builds preview deployments for UI-related pull requests

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#7]
Could probably use something like Vercel to deploy the UI itself. But we'd need a backend to run against which would be a little tougher. But gateway UI has mock API implementation so for starters we could just used a mocked-out backend.

**Comment by wbobeirne** [comment]
Another difficulty here is how stateful fedimintd is. Only one person looking at a preview deployment would be able to run through setup, then it would be stuck in the post-setup dashboard. I think the only way to reasonably do this is to have a way to spin up personal environments on demand, rather than one per PR.

**Comment by EthnTuttle** [comment]
> Another difficulty here is how stateful fedimintd is. Only one person looking at a preview deployment would be able to run through setup, then it would be stuck in the post-setup dashboard. I think the only way to reasonably do this is to have a way to spin up personal environments on demand, rather than one per PR.

This make me think more about expanding the scope and functionality of devimint. 🤔
Please solicit during dev call @justinmoon, if I'm not there.

**Comment by Kodylow** [comment]
With this we can just deploy it without the backend config api url set and just point it at whatever fedimintd you want, assigning eric for how he wants to add the preview deployment (talked about it live) https://github.com/fedimint/ui/pull/485

**Comment by elsirion** [comment]
Dup of https://github.com/fedimint/ui/issues/430
