### ISSUE TITLE
Guardian UI: Followers should watch for Leader to kick off DKG

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/ui#83]
We've run into a problem during some of our test setups that is easy to miss when you're developing solo, or setting up a 1 of 1 or 2 of 2 federation. Right now followers attempt to run DKG as soon as they approve the configuration. This is problematic if in e.g. a 2 of 3 federation, only the leader and follower 1 have joined. Follower 1 has not yet gotten any information about Follower 2 who will join shortly, so their DKG is incomplete. Once follower 2 attempts to run DKG, it'll fail because follower 1 will reject them.

We need to re-architect this so that followers go through the following flow:

1. Follower pastes in leaders WS API URL
2. Follower is presented with configuration from leader
3. Follower hits approve on configuration
4. Follower is presented with a screen that shows the status of all peers, and says that it's waiting for the leader to continue
5. Follower sees that the leader's status has gone from `SharingConfigGenParams` to `ReadyForConfigGen`
6. Follower transitions to the RunDKG screen and attempts to run DKG

Followers will not know how many guardians the leader intends for the federation to have, so they will not see the rows that indicate guardians that have not joined yet like the leader does.

**Comment by justinmoon** [comment]
As context, `run_dkg` just [fetches the peers from the database](https://github.com/fedimint/fedimint/blob/c10a9f9daa90ccdbadd04334ac870bd4d2ee96a1/fedimint-server/src/config/api.rs#L195)

**Comment by okjodom** [comment]
@justinmoon should we close this as fixed (server side) after https://github.com/fedimint/fedimint/pull/2782 ?
