### ISSUE TITLE
Clarify UI handling of Setup API teardown

### ISSUE THREAD

**Issue by garyray-k** [fedimint/ui#9]
The config server shuts down as we finalize the configuration of the federation, currently, we just use a timer to wait for the transition to happen on the backend.

 
>Yeah so the tricky thing is that once you start consensus, the config server shuts down and the regular api starts up, so it necessarily kills the socket. Ideally the config server would stay up long enough to respond to the rpc, indicating that it successfully started the server, and then shuts down. Worth an issue to improve the understandability of the code IMO.
>
>I haven't spent enough time here to know if this is a reasonable timeout, but you are correct that it could hypothetically not be enough time. Unfortunately while I was working on this, this part of starting consensus would cause the backend to panic and crash. Might be worth some retries if we find it's prone to taking longer than this.

_Originally posted by @wbobeirne in https://github.com/fedimint/fedimint/pull/2360#discussion_r1186997489_

**Comment by okjodom** [comment]
After `SetupComplete` screen, #28 introduced a full transition of Setup experience to Admin experience.
`SetupContext` and it's api is torn down and replaced by an admin scoped api in `AdminContext`.

This transition is one way, but we still need to clean up the local storage states written through setup. See #34
