### ISSUE TITLE
Gateway: Authentication

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#90]
This requires [backend change](https://github.com/fedimint/fedimint/issues/2786) to fully work.

- [ ] Create password screen
- [x] Authenticate later with ^^ password. This needs a design. Initial screen has options to "login" or "create password".

<img width="510" alt="image" src="https://github.com/fedimint/ui/assets/4335621/fdf43832-3072-4bee-aee9-889eec4a7f3f">

**Comment by justinmoon** [comment]
Somewhere here we need a loading state when we're calling `/info` to fetch our list of guardians. I'm putting the issue here because on the initial load we might need to do this to figure out whether to send them to the "connect federation" screen or the main admin screen.

**Comment by wbobeirne** [comment]
The backend for this is done so this is ready to be implemented. We should still support `REACT_APP_FM_GATEWAY_PASSWORD` env var as a password _default_, but the UI should handle if that password is incorrect and prompt the user to login allowing them to provide a different password.

**Comment by okjodom** [comment]
We need design clarification on the UIs for configuring / updating passwords, and for login.
#246 Is a partial fix that reuses login experience from Guardian UI

**Comment by justinmoon** [comment]
Status here @okjodom? Closed by https://github.com/fedimint/ui/pull/246?

**Comment by okjodom** [comment]
Think we need a 'create/update' password screen designed and implemented.ented? Pr only added a login screen which was a re-use of guardian UI experience

**Comment by benthecarman** [comment]
Can this be prioritized? Without this it basically makes using the gateway-ui a terrible security practice. While you are running the UI, if anyone has the URL they can get in and withdraw all the money. The only way to safely run this is behind some secure proxy which isn't really noted anywhere and isn't standard to most users.

**Comment by okjodom** [comment]
@Kodylow, do you have bandwidth for this? The gateway now has a set-configuration api that we can use to set/reset password

**Comment by Kodylow** [comment]
yup on it

**Comment by Kodylow** [comment]
@benthecarman I did a hotfix for this today, it was reading the client side password from the environment variable. Cutting a new release with it asap

**Comment by benthecarman** [comment]
Thanks, yeah I realized after this comment that you could exclude the env variable and it would prompt for the password, still seemed like a bad option to even expose though

**Comment by Kodylow** [comment]
I pushed a PR removing that, started on a separate one for updating password but also want that in guardian ui

**Comment by Kodylow** [comment]
closing, stale
