### ISSUE TITLE
Shared: SPA experience for MVP

### ISSUE THREAD

**Issue by okjodom** [fedimint/ui#92]
Guardian UI and Gateway UI share the same single page application background for MVP. This includes the 
- [x] Header (with Fedimint logo)
- [x] A slot for app-specific experience
- [x] A common footer experience.
- [x] Apply the common SPA in guardian ui
- [x] Apply the common SPA in gateway ui

![image](https://github.com/fedimint/ui/assets/11217077/8b0de0e0-7d62-449a-96da-31fc6aec25fe)

**Comment by IgboPharaoh** [comment]
#108

**Comment by okjodom** [comment]
@IgboPharaoh, could we reuse the same `guardian-ui` components introduced in #108 for the `gateway-ui` as well?

**Comment by IgboPharaoh** [comment]
Definitely, it was built in such a way it could be reusable across both ``guardian-ui`` and ``gateway-ui``, I'll raise a PR for moving #108 into @fedimint/ui since the design for both UIs uses the same page structure

**Comment by IgboPharaoh** [comment]
> @IgboPharaoh, could we reuse the same `guardian-ui` components introduced in #108 for the `gateway-ui` as well?

#117

**Comment by IgboPharaoh** [comment]
#127  - ``Apply the common SPA in gateway ui``
