### ISSUE TITLE
Gateway: Flatten admin experience into SPA

### ISSUE THREAD

**Issue by okjodom** [fedimint/ui#93]
- [x] Flatten gateway info tab into the Gateway admin experience SPA
- [x] Flatten Deposit experience tab ''
- [x] Flatten Withdraw experience tab

![image](https://github.com/fedimint/ui/assets/11217077/7c9f47ff-ab03-46d9-b1f1-451730cc39f6)

**Comment by IgboPharaoh** [comment]
Hello @okjodom  I'll like to work on this issue

**Comment by IgboPharaoh** [comment]
#119

**Comment by okjodom** [comment]
We can follow up with a bunch of code cleanups :)
